%% Final White Box Functional Decomposition Figure
% Stable axes-based version: boxes, text, and arrows are drawn in axes coordinates.

clear
clc
close all
clear functions

cd("C:\Users\USER\Desktop\github\UrbanEV_BBW_FRESH")

if ~isfolder("figures")
    mkdir("figures")
end

if isfile("matlab.mat")
    delete("matlab.mat")
end

set(groot,'defaultTextInterpreter','none')
set(groot,'defaultLegendInterpreter','none')
set(groot,'defaultAxesTickLabelInterpreter','none')

%% Colors
fontName = "Arial";

blueEdge   = [0.12 0.38 0.70];
blueFill   = [0.91 0.96 1.00];

orangeEdge = [0.85 0.42 0.08];
orangeFill = [1.00 0.94 0.82];

grayEdge   = [0.45 0.45 0.45];
grayFill   = [0.97 0.97 0.97];

darkText   = [0.08 0.08 0.08];

%% Figure and axes
fig = figure( ...
    "Color","w", ...
    "Units","pixels", ...
    "Position",[100 80 1600 900], ...
    "Renderer","painters");

set(fig,"InvertHardcopy","off")
set(fig,"PaperPositionMode","auto")

ax = axes("Position",[0 0 1 1]);
axis(ax,[0 100 0 100])
axis(ax,"off")
hold(ax,"on")

% White background
rectangle(ax, ...
    "Position",[0 0 100 100], ...
    "FaceColor","w", ...
    "EdgeColor","w")

%% Title and subtitle
text(ax,50,91, ...
    "White Box Functional Decomposition", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",24, ...
    "FontWeight","bold", ...
    "Color",darkText)

text(ax,50,86, ...
    "The black-box brake-request logic is decomposed into internal functions", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",13, ...
    "Color",darkText)

text(ax,50,76, ...
    "Main Functional Flow", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",14, ...
    "FontWeight","bold", ...
    "Color",blueEdge)

%% Main function boxes
topY = 60;
boxW = 13.5;
boxH = 10.5;

xF01 = 7;
xF02 = 24;
xF05 = 43.25;
xF06 = 60.25;
xF07 = 77.25;

topXs = [xF01 xF02 xF05 xF06 xF07];

topLabels = {
    sprintf("F-01\nReceive\nScenario Inputs")
    sprintf("F-02\nNormalize\nScenario Data")
    sprintf("F-05\nClassify\nWarning State")
    sprintf("F-06\nGenerate\nBrake Request")
    sprintf("F-07\nVerify and\nLog Result")
};

for i = 1:numel(topXs)
    rectangle(ax, ...
        "Position",[topXs(i) topY boxW boxH], ...
        "FaceColor",blueFill, ...
        "EdgeColor",blueEdge, ...
        "LineWidth",1.8, ...
        "Curvature",0.04)

    text(ax,topXs(i)+boxW/2,topY+boxH/2,topLabels{i}, ...
        "HorizontalAlignment","center", ...
        "VerticalAlignment","middle", ...
        "FontName",fontName, ...
        "FontSize",10.8, ...
        "FontWeight","bold", ...
        "Color",darkText)
end

%% Risk-estimation boxes
riskY = 36;
riskW = 17.5;
riskH = 9.5;

xF03 = 32;
xF04 = 53;

rectangle(ax, ...
    "Position",[xF03 riskY riskW riskH], ...
    "FaceColor",orangeFill, ...
    "EdgeColor",orangeEdge, ...
    "LineWidth",1.8, ...
    "Curvature",0.04)

text(ax,xF03+riskW/2,riskY+riskH/2, ...
    sprintf("F-03\nEstimate\nStopping Distance"), ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",10.5, ...
    "FontWeight","bold", ...
    "Color",darkText)

rectangle(ax, ...
    "Position",[xF04 riskY riskW riskH], ...
    "FaceColor",orangeFill, ...
    "EdgeColor",orangeEdge, ...
    "LineWidth",1.8, ...
    "Curvature",0.04)

text(ax,xF04+riskW/2,riskY+riskH/2, ...
    sprintf("F-04\nEstimate\nTime-to-Collision"), ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",10.5, ...
    "FontWeight","bold", ...
    "Color",darkText)

text(ax,51.5,50.2, ...
    "Risk Estimation Functions", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",12.5, ...
    "FontWeight","bold", ...
    "Color",orangeEdge)

%% Main blue arrows
mainArrowY = topY + boxH/2;

quiver(ax, xF01+boxW, mainArrowY, xF02-(xF01+boxW), 0, 0, ...
    "Color",blueEdge, "LineWidth",1.6, "MaxHeadSize",0.35)

quiver(ax, xF02+boxW, mainArrowY, xF05-(xF02+boxW), 0, 0, ...
    "Color",blueEdge, "LineWidth",1.6, "MaxHeadSize",0.35)

quiver(ax, xF05+boxW, mainArrowY, xF06-(xF05+boxW), 0, 0, ...
    "Color",blueEdge, "LineWidth",1.6, "MaxHeadSize",0.35)

quiver(ax, xF06+boxW, mainArrowY, xF07-(xF06+boxW), 0, 0, ...
    "Color",blueEdge, "LineWidth",1.6, "MaxHeadSize",0.35)

%% Orange dependency arrows
% Required logic:
% F-02 -> F-03
% F-02 -> F-04
% F-03 -> F-05
% F-04 -> F-05

% F-02 bottom center to F-03 top center
startX = xF02 + boxW*0.50;
startY = topY;
endX   = xF03 + riskW*0.50;
endY   = riskY + riskH;
quiver(ax,startX,startY,endX-startX,endY-startY,0, ...
    "Color",orangeEdge,"LineWidth",1.45,"MaxHeadSize",0.30)

% F-02 bottom right to F-04 top left/center
startX = xF02 + boxW*0.70;
startY = topY;
endX   = xF04 + riskW*0.48;
endY   = riskY + riskH;
quiver(ax,startX,startY,endX-startX,endY-startY,0, ...
    "Color",orangeEdge,"LineWidth",1.45,"MaxHeadSize",0.30)

% F-03 top right to F-05 bottom left
startX = xF03 + riskW*0.78;
startY = riskY + riskH;
endX   = xF05 + boxW*0.42;
endY   = topY;
quiver(ax,startX,startY,endX-startX,endY-startY,0, ...
    "Color",orangeEdge,"LineWidth",1.45,"MaxHeadSize",0.30)

% F-04 top left to F-05 bottom right
startX = xF04 + riskW*0.28;
startY = riskY + riskH;
endX   = xF05 + boxW*0.58;
endY   = topY;
quiver(ax,startX,startY,endX-startX,endY-startY,0, ...
    "Color",orangeEdge,"LineWidth",1.45,"MaxHeadSize",0.30)

%% Footer interpretation
rectangle(ax, ...
    "Position",[20 15 60 8.5], ...
    "FaceColor",grayFill, ...
    "EdgeColor",grayEdge, ...
    "LineWidth",1.2, ...
    "Curvature",0.025)

text(ax,50,19.25, ...
    sprintf("Interpretation: normalized scenario data feed the supporting risk-estimation functions.\nTheir outputs contribute to warning-state classification, brake-request generation, and final result logging."), ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "FontName",fontName, ...
    "FontSize",10.5, ...
    "Color",darkText)

%% Export
outFile = "figures/white_box_functional_decomposition.png";
exportgraphics(fig,outFile,"Resolution",350)

disp("Final White Box Functional Decomposition figure created successfully.")
disp("Saved to: " + outFile)