clc;
clear;
close all;

% Create output folder if it does not exist
if ~exist('figures','dir')
    mkdir('figures');
end

% -----------------------------
% Color palette
% -----------------------------
blueEdge   = [0.12 0.40 0.80];
blueFill   = [0.90 0.95 1.00];

orangeEdge = [0.90 0.45 0.05];
orangeFill = [0.97 0.91 0.78];

grayEdge   = [0.50 0.50 0.50];
grayFill   = [0.97 0.97 0.97];

darkText   = [0.10 0.10 0.10];
titleBlue  = [0.18 0.40 0.78];

fontName = 'Arial';

% -----------------------------
% Figure
% -----------------------------
fig = figure('Color','w', ...
    'Units','pixels', ...
    'Position',[80 50 1800 950]);

% -----------------------------
% Title and subtitle
% -----------------------------
annotation('textbox',[0.20 0.905 0.60 0.055], ...
    'String','White Box Functional Decomposition', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',30, ...
    'FontWeight','bold', ...
    'Color',darkText);

annotation('textbox',[0.22 0.855 0.56 0.040], ...
    'String','The black-box brake-request logic is decomposed into internal functions', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',16, ...
    'Color',darkText);

annotation('textbox',[0.38 0.74 0.24 0.035], ...
    'String','Main Functional Flow', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'Color',titleBlue);

% -----------------------------
% Box positions
% -----------------------------
topY  = 0.56;
topW  = 0.14;
topH  = 0.11;
topX  = [0.07 0.245 0.42 0.595 0.77];

botY  = 0.33;
botW  = 0.18;
botH  = 0.105;
botX  = [0.31 0.54];

% -----------------------------
% Top row boxes
% -----------------------------
topText = {
    sprintf('F-01\nReceive\nScenario Inputs')
    sprintf('F-02\nNormalize\nScenario Data')
    sprintf('F-05\nClassify\nWarning State')
    sprintf('F-06\nGenerate\nBrake Request')
    sprintf('F-07\nVerify and\nLog Result')
};

for i = 1:numel(topX)
    annotation('textbox',[topX(i) topY topW topH], ...
        'String',topText{i}, ...
        'EdgeColor',blueEdge, ...
        'FaceColor',blueFill, ...
        'LineWidth',2.0, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',fontName, ...
        'FontSize',15, ...
        'FontWeight','bold', ...
        'Color',darkText);
end

% -----------------------------
% Bottom row boxes
% -----------------------------
bottomText = {
    sprintf('F-03\nEstimate\nStopping Distance')
    sprintf('F-04\nEstimate\nTime-to-Collision')
};

for i = 1:numel(botX)
    annotation('textbox',[botX(i) botY botW botH], ...
        'String',bottomText{i}, ...
        'EdgeColor',orangeEdge, ...
        'FaceColor',orangeFill, ...
        'LineWidth',2.0, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontName',fontName, ...
        'FontSize',15, ...
        'FontWeight','bold', ...
        'Color',darkText);
end

% Optional label for lower block group
annotation('textbox',[0.39 0.435 0.22 0.035], ...
    'String','Supporting Risk Estimation', ...
    'EdgeColor','none', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color',orangeEdge);

% -----------------------------
% Main blue flow arrows
% F-01 -> F-02 -> F-05 -> F-06 -> F-07
% -----------------------------
for i = 1:4
    x1 = topX(i) + topW;
    x2 = topX(i+1);
    y1 = topY + topH/2;
    y2 = y1;

    annotation('arrow',[x1 x2],[y1 y2], ...
        'Color',blueEdge, ...
        'LineWidth',1.8, ...
        'HeadLength',9, ...
        'HeadWidth',9);
end

% -----------------------------
% Orange support arrows
% IMPORTANT:
% keep F-02 -> F-03
% keep F-02 -> F-04
% keep F-03 -> F-05
% keep F-04 -> F-05
% -----------------------------

% F-02 -> F-03
annotation('arrow', ...
    [topX(2)+topW*0.55 , botX(1)+botW*0.45], ...
    [topY               , botY+botH          ], ...
    'Color',orangeEdge, ...
    'LineWidth',1.8, ...
    'HeadLength',9, ...
    'HeadWidth',9);

% F-02 -> F-04
annotation('arrow', ...
    [topX(2)+topW*0.60 , botX(2)+botW*0.52], ...
    [topY               , botY+botH         ], ...
    'Color',orangeEdge, ...
    'LineWidth',1.8, ...
    'HeadLength',9, ...
    'HeadWidth',9);

% F-03 -> F-05
annotation('arrow', ...
    [botX(1)+botW*0.58 , topX(3)+topW*0.47], ...
    [botY+botH         , topY              ], ...
    'Color',orangeEdge, ...
    'LineWidth',1.8, ...
    'HeadLength',9, ...
    'HeadWidth',9);

% F-04 -> F-05
annotation('arrow', ...
    [botX(2)+botW*0.42 , topX(3)+topW*0.53], ...
    [botY+botH         , topY              ], ...
    'Color',orangeEdge, ...
    'LineWidth',1.8, ...
    'HeadLength',9, ...
    'HeadWidth',9);

% -----------------------------
% Interpretation box
% -----------------------------
annotation('textbox',[0.20 0.125 0.60 0.10], ...
    'String',{ ...
    'Interpretation: normalized scenario data feed the supporting risk-estimation functions,', ...
    'whose outputs contribute to warning-state classification, brake-request generation, and final result logging.'}, ...
    'EdgeColor',grayEdge, ...
    'FaceColor',grayFill, ...
    'LineWidth',1.5, ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','middle', ...
    'FontName',fontName, ...
    'FontSize',13.5, ...
    'Color',darkText);

% -----------------------------
% Export
% -----------------------------
outFile = fullfile('figures','white_box_functional_decomposition.png');
exportgraphics(fig,outFile,'Resolution',350);

disp('White box functional decomposition figure created successfully.');
disp(['Saved to: ' outFile]);