clear; clc; close all;

% ============================================================
% UrbanEV-BBW-RFLP-Verification
% Main execution script
% ============================================================

script_folder = fileparts(mfilename('fullpath'));
root = fileparts(script_folder);

addpath(script_folder);

data_folder = fullfile(root, "data");
results_folder = fullfile(root, "results");
figures_folder = fullfile(root, "figures");

if ~exist(results_folder, "dir")
    mkdir(results_folder);
end

if ~exist(figures_folder, "dir")
    mkdir(figures_folder);
end

fprintf("\nRunning UrbanEV-BBW-RFLP-Verification project...\n");

% ------------------------------------------------------------
% 1. Load input data
% ------------------------------------------------------------

concepts = readtable(fullfile(data_folder, "vehicle_concepts.csv"));
scenarios = readtable(fullfile(data_folder, "scenarios.csv"));
actuators = readtable(fullfile(data_folder, "actuator_candidates.csv"));

% ------------------------------------------------------------
% 2. Vehicle concept selection
% ------------------------------------------------------------

concept_results = concept_selection_model(concepts);
writetable(concept_results, fullfile(results_folder, "concept_selection_results.csv"));

selected_concept = concept_results(concept_results.decision == "Selected", :);

% ------------------------------------------------------------
% 3. Scenario-based verification
% ------------------------------------------------------------

scenario_results = bbw_emergency_braking_controller(scenarios);
writetable(scenario_results, fullfile(results_folder, "scenario_verification_results.csv"));

% ------------------------------------------------------------
% 4. Actuator concept selection
% ------------------------------------------------------------

actuator_results = actuator_concept_selection(actuators);
writetable(actuator_results, fullfile(results_folder, "actuator_selection_results.csv"));

selected_actuator = actuator_results(actuator_results.decision == "Selected", :);

% ------------------------------------------------------------
% 5. Traceability matrix
% ------------------------------------------------------------

traceability = table( ...
    ["REQ-VEH-01"; ...
     "REQ-VEH-02"; ...
     "REQ-VEH-03"; ...
     "REQ-BBW-01"; ...
     "REQ-BBW-02"; ...
     "REQ-BBW-03"; ...
     "REQ-BBW-04"; ...
     "REQ-BBW-05"; ...
     "REQ-BBW-06"; ...
     "REQ-BBW-07"], ...
    ["F1"; ...
     "F2"; ...
     "F2"; ...
     "F3, F7"; ...
     "F4"; ...
     "F5"; ...
     "F6"; ...
     "F7"; ...
     "F8"; ...
     "F9"], ...
    ["L1"; ...
     "L2"; ...
     "L1"; ...
     "L3, L7"; ...
     "L4"; ...
     "L5"; ...
     "L6"; ...
     "L7"; ...
     "L8"; ...
     "L9"], ...
    ["P1"; ...
     "P1"; ...
     "P1"; ...
     "P2, P5, P7"; ...
     "P4, P7"; ...
     "P6, P7"; ...
     "P2, P5, P7"; ...
     "P5, P7"; ...
     "P5"; ...
     "P7"], ...
    ["Concept data review"; ...
     "Range model"; ...
     "Decision matrix"; ...
     "SCN-01 to SCN-06"; ...
     "SCN-01 to SCN-06"; ...
     "SCN-01 to SCN-06"; ...
     "SCN-05"; ...
     "SCN-06"; ...
     "Actuator selection"; ...
     "Traceability review"], ...
    'VariableNames', { ...
    'requirement_id', ...
    'function_id', ...
    'logical_block_id', ...
    'physical_or_concept_element', ...
    'scenario_or_test'});

writetable(traceability, fullfile(results_folder, "traceability_matrix.csv"));

% ------------------------------------------------------------
% 6. Figures
% ------------------------------------------------------------

figure;
bar(categorical(string(concept_results.concept_id)), concept_results.total_score);
xlabel("Vehicle Concept");
ylabel("Total Score");
title("Vehicle Concept Selection Score");
grid on;
saveas(gcf, fullfile(figures_folder, "vehicle_concept_comparison.png"));

state_numeric = zeros(height(scenario_results), 1);

for i = 1:height(scenario_results)
    switch string(scenario_results.warning_state(i))
        case "SAFE"
            state_numeric(i) = 1;
        case "CAUTION"
            state_numeric(i) = 2;
        case "WARNING"
            state_numeric(i) = 3;
        case "EMERGENCY_BRAKE"
            state_numeric(i) = 4;
    end
end

figure;
bar(categorical(string(scenario_results.scenario_id)), state_numeric);
xlabel("Scenario");
ylabel("Warning Level");
title("Scenario-Based Warning State Summary");
yticks([1 2 3 4]);
yticklabels(["SAFE", "CAUTION", "WARNING", "EMERGENCY_BRAKE"]);
grid on;
saveas(gcf, fullfile(figures_folder, "scenario_verification_summary.png"));

% ------------------------------------------------------------
% 7. Verification summary
% ------------------------------------------------------------

summary_path = fullfile(results_folder, "verification_summary.md");
fid = fopen(summary_path, "w");

fprintf(fid, "# Verification Summary\n\n");

fprintf(fid, "## Selected Vehicle Concept\n\n");
fprintf(fid, "Selected concept: %s\n\n", string(selected_concept.concept_id));
fprintf(fid, "Description: %s\n\n", string(selected_concept.description));
fprintf(fid, "Estimated range: %.2f km\n\n", selected_concept.estimated_range_km);
fprintf(fid, "Total concept score: %.2f\n\n", selected_concept.total_score);

fprintf(fid, "## Selected Actuator Candidate\n\n");
fprintf(fid, "Selected actuator: %s\n\n", string(selected_actuator.actuator_id));
fprintf(fid, "Concept: %s\n\n", string(selected_actuator.concept));
fprintf(fid, "Total actuator score: %.2f\n\n", selected_actuator.total_score);

fprintf(fid, "## Scenario Verification\n\n");
for i = 1:height(scenario_results)
    fprintf(fid, "- %s: state = %s, TTC = %.2f s, stopping distance = %.2f m, brake_request = %d, result = %s\n", ...
        string(scenario_results.scenario_id(i)), ...
        string(scenario_results.warning_state(i)), ...
        scenario_results.ttc_s(i), ...
        scenario_results.stopping_distance_m(i), ...
        scenario_results.brake_request(i), ...
        string(scenario_results.verification_result(i)));
end

fprintf(fid, "\n## Scope Note\n\n");
fprintf(fid, "This project follows a lightweight MBSE/RFLP workflow suitable for university-level concept design and MATLAB-based scenario verification. ");
fprintf(fid, "It does not claim complete industrial MBSE implementation or production-ready brake-by-wire design.\n");

fclose(fid);

fprintf("\nProject execution completed successfully.\n");
fprintf("Results saved in: %s\n", results_folder);
fprintf("Figures saved in: %s\n", figures_folder);